apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault-deployment
  namespace: tools
spec:
  ports:
    - name: vault
      port: 8082
      targetPort: 8200
  selector:
    app: vault-deployment
  type: NodePort